#!/bin/bash

# QUICK DEPLOYMENT COMMANDS
# Copy these commands and run on the server at /root/sportsbook-minimal

echo "=== Quick Frontend Rebuild ==="
echo ""
echo "Run these commands on the server:"
echo ""
echo "cd /root/sportsbook-minimal"
echo ""
echo "# Download the rebuild script from repo (if not already there)"
echo "# Or copy rebuild-frontend.sh to this directory"
echo ""
echo "# Make it executable"
echo "chmod +x rebuild-frontend.sh"
echo ""
echo "# Run the rebuild"
echo "./rebuild-frontend.sh"
echo ""
echo "=== OR Manual Commands ==="
echo ""
echo "cd /root/sportsbook-minimal"
echo "docker compose stop arb-ui"
echo "docker compose rm -f arb-ui"
echo "docker rmi sportsbook-minimal-ui 2>/dev/null || true"
echo "docker compose build --no-cache ui"
echo "docker compose up -d ui"
echo ""
echo "# Verify"
echo "docker exec arb-ui cat /usr/share/nginx/html/index.html | grep assets"
echo ""
